### ISSUE TITLE
A demuxer for this container (mp3) was not found [w/gh-pages example]

### ISSUE THREAD

**Issue by NHQ** [audiocogs/aurora.js#101]
if you [go here](http://nhq.github.io/aurora-test/) and open the dev console, you will see the error

the source code is here:  https://github.com/NHQ/aurora-test/blob/gh-pages/bundle.js
the audio file is here: http://nhq.github.io/aurora-test/audio.mp3

I used builds for aurora, aac and mp3 following the instructions.

**Comment by devongovett** [comment]
This happens because browserify uses `.js` files over `.coffee` files when building. If you run a `make clean` before `make browser` it will work because the `.js` files are removed.
