### ISSUE TITLE
Audio Encoding

### ISSUE THREAD

**Issue by chris-rudmin** [audiocogs/aurora.js#112]
I am interested in writing some code so that aurora.js might support encoding and muxing a file.

My end goal is to [record the microphone input](https://github.com/chris-rudmin/Recorderjs) and encode using OPUS into an OGG container for a smaller transfer size.
My approach is going to be:

1. Add a Muxers and Encoders Class referencing Demuxers and Decoders structure.
2. Update opus.js and ogg.js to support muxers and encoder

Would there be any interest in merging such a feature?
Any pitfalls I should be aware of before undertaking such an endeavour?

**Comment by devongovett** [comment]
Closing for #72.
