### ISSUE TITLE
Asset/Player HTTPSource fails when HTTP response has no Content-Length, or is cached

### ISSUE THREAD

**Issue by wsot** [audiocogs/aurora.js#113]
When trying to load an asset using fromURL, if the server doesn't provide content-length for the file the file isn't downloaded or if the file is cached (because loading a cached file doesn't seem to provide a Content-Length)

The issue seems to originate from the following code (which I've patched to make it work but it is a super-dodgy patch; it gives the idea of the problem, though):

    --- aurora.js   2014-11-27 11:09:05.000000000 +1100
    +++ aurora.mod.js   2014-11-27 11:33:27.000000000 +1100
    @@ -3788,7 +3788,8 @@ HTTPSource = (function(_super) {

       HTTPSource.prototype.loop = function() {
         var endPos;
    -    if (this.inflight || !this.length) {
    +    if (this.inflight) {
    +    //if (this.inflight || !this.length) {
           return this.emit('error', 'Something is wrong in HTTPSource.loop');
         }
         this.inflight = true;
    @@ -3805,16 +3806,24 @@ HTTPSource = (function(_super) {
                 buf[i] = txt.charCodeAt(i) & 0xff;
               }
             }
    +
             buffer = new AVBuffer(buf);
             _this.offset += buffer.length;
             _this.emit('data', buffer);
    -        if (_this.offset >= _this.length) {
    -          _this.emit('end');
    +        if ((!_this.length && _this.xhr.readyState==4) ||

**Comment by devongovett** [comment]
Yeah, we need Content-Length so we can make Range requests for the file, since XMLHttpRequest doesn't support proper streaming. Hopefully that's coming soon with the fetch api.

**Comment by renanyoy** [comment]
aurora.js can't decode audio stream, like radio (eg: shoutcast/icecast) ?
