### ISSUE TITLE
Nothing's happening?  What am I missing?

### ISSUE THREAD

**Issue by whmountains** [audiocogs/aurora.js#115]
When I run the code, nothing happens and the node process exits after a few seconds.  I'm guessing I'm not "hooking up" the player to the decoder properly, but I can't find any information confirming or denying that.

This is mac os 10.10 with node v0.10.31
```
var AV = require('av');
var mp3 = require('mp3');

var player = AV.Player.fromFile('./t1.mp3');

player.play();
```

**Comment by darxides** [comment]
I'm writing the same code as yours and it gives me "No supported audio device found" error

**Comment by master255** [comment]
@darxides try to read my article http://habrahabr.ru/post/222729/

**Comment by darxides** [comment]
@whmountains Now I figured it out.
At first ```var AV = require('av');``` gave me error, so I just loaded the [script](https://github.com/audiocogs/aurora.js/releases) in head like this
```<script src="./js/aurora.js"></script>```
Then, you can't just type the filename in ```AV.Player.fromFile()```. It works with browser File API. It means you have to choose your file using ```<input type="file">``` (I'm not sure). But ```AV.Player.fromURL()``` worked fine for me, so I found way to create urls for local files. I have created server for this purpose. At first you should install node-static ```npm install node-static```
Then place this code in your app
```
var static = require('node-static');
var file = new static.Server('C://Yourapp/whatever');
require('http').createServer(function (request, response) {
    request.addListener('end', function () {
        file.serve(request, response);
    }).resume();
}).listen(8080);
```
now you can use
```
var player = AV.Player.fromURL('http://localhost:8080/t1.mp3');
player.play();
```

**Comment by darxides** [comment]
@master255 там в статье используется DOM File API, а как загружать файл используя node js filesystem не пойму никак. В способе, который я выше изложил перед проигрыванием возникает задержка секунды в 4, а в конце файл обрезается секунд на 10. То ли я что-то неправильно делаю, то ли проблема в авроре
