### ISSUE TITLE
Decode to AudioBuffer?

### ISSUE THREAD

**Issue by nmgtn** [audiocogs/aurora.js#122]
I'm having success loading an audio file into an Asset object with `AV.Asset.fromURL('test.wav')`, and then using the `decodeToBuffer` method to decode the audio file. However, what comes out of that method is just a float array.

My end game is to use aurora as a substitute for the `decodeAudioData` method in the Web Audio API, because I can get Aurora to support FLAC and other file formats that aren't natively supported. I'd like to get an AudioBuffer object that I can then feed in to other processes, but just use Aurora to decode the file to the AudioBuffer rather than the native method in the Web Audio API.

Is this already possible in any with Aurora? I have tried myself to implement something but it doesn't seem to be working. I think it may be falling down where I try to deinterleave the array that comes back from Aurora so I can feed it to separate channels of the AudioBuffer object. I'm not sure though, as my debugging skills are a bit lacking!

If there is no way of doing this currently in Aurora, if you give me some tips on avenues I could pursue, I will do my best to get it going and then see if I can put together a pull request to extend Aurora in this way.

**Comment by mon** [comment]
It's a little messy, because the Aurora buffer is interleaved.

    var asset = AV.Asset.fromBuffer(someArrayBuffer);
    asset.on("error", function(err) {
        console.log(err);
    });
    asset.decodeToBuffer(function(buffer) {
        var channels = asset.format.channelsPerFrame;
        var samples = buffer.length/channels;
        var audioBuf = this.context.createBuffer(channels, samples, asset.format.sampleRate);
        var audioChans = [];
        for(var i = 0; i < channels; i++) {
            audioChans.push(audioBuf.getChannelData(i));
        }
        for(var i = 0; i < buffer.length; i++) {
            audioChans[i % channels][Math.round(i/channels)] = buffer[i];
        }
        // Do something with your fancy new audioBuffer
    });
