### ISSUE TITLE
Playing FLAC on server requires 100% buffer

### ISSUE THREAD

**Issue by richardlevy** [audiocogs/aurora.js#124]
Hi,

I'm trying to use Aurora with FLAC.js to play a FLAC stream (http) from Subsonic (on a local network).

I can get it to play OK, however, it doesn't play correctly until the buffer is at 100% (I start a preload() after creating the player).  According to the Subsonic log, this is when it's sent it the entire file.  This is not ideal for streaming as I don't want to have gaps in playback.

If I call play() before the buffer is at 100%, I get this warning

`[../deps/mpg123/src/output/coreaudio.c:81] warning: Didn't have any audio data in callback (buffer underflow)`

It tries to play, but the audio is broken up.

Is there a setting I'm missing, or is this expected behavior?

Thanks
Rich

**Comment by crackofdusk** [comment]
Hey,

Take a look at https://github.com/fsbdev/aurora-websocket and the discussion that led to it: https://github.com/audiocogs/aurora.js/pull/32

**Comment by richardlevy** [comment]
Hi,

thanks for the link - but even the author of the web socket plugin has the same issue with delay before playback?  No hint of a fix/workaround or otherwise?

Thanks
Rich

**Comment by richardlevy** [comment]
Update on this - I think the audio is broken up **while** its buffering.

I noticed this in the following scenario:

I have 2 players, current and next.  If I current.play() while next is preloading, the audio from current is broken up until next has buffered 100%.

So, the issue is not that it won't play the file until it's pre-loaded, rather the preloading seems to interrupt playback.  And it's not localized to a player instance (as I saw in my test).

**Comment by fsbdev** [comment]
I only had the issue before I added throttling to the server https://github.com/fsbdev/aurora-websocket/blob/master/server-examples/node/aurora-ws-server.coffee#L45

**Comment by richardlevy** [comment]
Brilliant. Thanks very much!

**Comment by richardlevy** [comment]
To follow up, I've forked Aurora.js and added a rate limited HTTP source - code can be found here - https://github.com/richardlevy/aurora.js/blob/master/src/sources/node/httpLimited.coffee

By limiting the speed of the incoming stream, FLAC plays perfectly.

Thanks again.
