### ISSUE TITLE
Node - can play FLAC but not WAV stream

### ISSUE THREAD

**Issue by richardlevy** [audiocogs/aurora.js#126]
Hi,

me again!

I've written a Node app that plays a FLAC stream fine, but now I want to support WAV and I just get no sound.

There are no errors reported, and I can see the server streaming the data.  I've opened the stream in VLC and it plays fine, and confirmed its a LPCM stream.  

The player itself knows it's not playing since the currentTime is not advancing.

Am I missing something?

Thanks
Rich

**Comment by imShara** [comment]
Node-js app to play music? Did you mean node-webkit app?

**Comment by richardlevy** [comment]
Yes, playing on the server.  FLAC is fine (with FLAC.js), but won't play a PCM stream, which should be supported just with Aurora.js

**Comment by imShara** [comment]
I think it wrong, overkill way. Why can't you use native and extra lightweight [MPD](http://www.musicpd.org/) on server to play music and [drive it](https://github.com/andrewrk/mpd.js) with node?

**Comment by richardlevy** [comment]
Not seen that - thanks.

However, what I am doing is lightweight, and Aurora should be able to play a PCM stream.

**Comment by devongovett** [comment]
What platform are you on? If Linux, you'll need to install the ALSA header:

```
sudo apt-get install libasound2-dev
```

See https://github.com/TooTallNate/node-speaker#installation.

**Comment by richardlevy** [comment]
Hi

this is on Mac.

Although VLC reports the stream as WAV, I've had another audio framework that is unable to play the stream also.

I have worked around this now, so this issue can be closed.

Cheers
Rich
