### ISSUE TITLE
An question about  AV.Player.fromBuffer().Can anyone help me? Thanks!!

### ISSUE THREAD

**Issue by aizhilong** [audiocogs/aurora.js#127]
#### I use Node.js and Socket.io  to transmit MP3 buffer which record from an  android device.I don't know how to play it exactly.I have tried this:

    Server:  socket.emit("start", data.chunk);(data.chunk is mp3 buffer)

    Client:  socket.on("start", function(data){
                  var player = new AV.Player.fromBuffer ( data );
                   player.play();
                         })

   In this way,i only can get one buffer to play.  But the mp3 buffer is persistent,so the socket event is also persistent。who can tell me how to solve it?

**Comment by fsbdev** [comment]
You will have to create a new Source class that can read from your socket io stream, probably something similar to the Source class I made for plain websockets. https://github.com/fsbdev/aurora-websocket

**Comment by fsbdev** [comment]
This is the part where it actually creates the buffer data from the socket data https://github.com/fsbdev/aurora-websocket/blob/master/src/aurora-websocket.coffee#L56

**Comment by aizhilong** [comment]
But I  get real-time buffer from android device and the server just  transpond the buffer,no file created in the process.

**Comment by fsbdev** [comment]
That doesn't matter, my comment was about the client implementation, you will have to create a Source class.

**Comment by aizhilong** [comment]
Sorry,i still don't know how to do.i know little about JS.Can you give me a qq? i want talk with you if you have time.
