### ISSUE TITLE
How to preload/play multiple tracks at once?

### ISSUE THREAD

**Issue by Qqwy** [audiocogs/aurora.js#129]
I'm building a simple app that uses Aurora.
I'm preloading multiple songs from the server at once, asynchronously, and try to play them in a playlist, each of them being a separate player object that is initialized with new AV.Player.fromUrl() and player.preload(). However, once the later songs have started playing, the older (previously (partly) played) songs will not produce any sound anymore.
It seems that the Audio Device gets overwritten somewhere, although I might be incorrect with this assumption.

How to fix this? How to use Aurora with multiple players at once?

**Comment by MathijsvVelde** [comment]
Most of the time i have 3 players loaded
```
mainPlayer : {},
navPlayers : {
	prevPlayer : {},
	nextPlayer : {}
	},
```

I use the self build callbacks.
I trigger the loading for the 'next' track when the 'current' track is fully buffered and the 'previous' track when the 'next' track is playable.
When the 'current' track ends, I just move the players around and load a new 'next' player.
Though I use a NodeJs WebSocket (ws), you should be able to achieve the same if you use assets and assign them to the player when you need them

I hope this helps
