### ISSUE TITLE
A demuxer for this container was not found.

### ISSUE THREAD

**Issue by stkevintan** [audiocogs/aurora.js#130]
I use aurora in Node.js，It's perfect when playing local files,but when it comes to http sources, I encounter a error : ' A demuxer for this container was not found. '
here is my code:
```Javascript
var AV = require('av');
var mp3 = require('mp3');
var player = AV.Player.fromURL("http://7xiyak.com1.z0.glb.clouddn.com/MySoul.mp3");
player.play();
player.on('error', function (err) {
    console.log(err); // A demuxer for this container was not found.
});
```
anyone can help me ?

**Comment by devongovett** [comment]
Unfortunately, the way aurora currently works requires it to be able to detect the container within the first chunk of the file received. It probably gets a bigger first chunk from the file source than the HTTP source, and the mp3 probably has a large ID3 section at the beginning, preventing the MP3 demuxer from detecting it properly within the first chunk. Hope that makes sense.

**Comment by stkevintan** [comment]
it works fine when I put the same code into a html file. but I still get an error in node.js. it there some thing I missed? I simplely install aurora and mp3

**Comment by stkevintan** [comment]
a large ID3 section

**Comment by stkevintan** [comment]
by the way, is there any way to fix the problem?

**Comment by puluch** [comment]
I have the same problem here, large ID3 sections results in a "A demuxer for this container was not found". Is it possible to set a bigger first chunk of files ? Or isn't it that simple ?

**Comment by devongovett** [comment]
See #97.

**Comment by gpsamson** [comment]
I'm running into this issue when trying to get the format of a WAV file hosted on AWS S3. I've tried with both `fromUrl` and `fromBuffer`. 

Anyone come across this error and survive?
