### ISSUE TITLE
How to replay a song when play end?

### ISSUE THREAD

**Issue by cjd6568358** [audiocogs/aurora.js#131]
I want to implement the loop mode ,and i listened "end" event ,call the player play method but it doesn't work?

this.player.on('end', function () {
        this.play();
});

**Comment by puluch** [comment]
To make this work i give to the player again informations about my file/blob/URL. For example, i stock my file path in a var then call back the player (in a global var). I'm not using it to replay a song but to make a playlist so the path is changing at every end event.

For example i think this can work to create a loop : 

var player; 
function playfile(filePath){
     player=AV.Player.fromFile(filePath);
     player.play();
     player.on('end', function(){
          playfile(filePath);
     });
}
playfile('enter your file path here!');

I haven't try but hope it will help you!

**Comment by ikorchynskyi** [comment]
This works for me:
```javascript
player.on('end', function() {
    setTimeout(function() {
        player.startPlaying();
        player.seek(0);
        player.play();
    }, 5);
});
```

Looks like the root of the issue is in calling `Player.stop` right after emitting `end` event in `Player.startPlaying`
