### ISSUE TITLE
Visualisation making

### ISSUE THREAD

**Issue by puluch** [audiocogs/aurora.js#132]
Hey, does someone has any clue on how to return something (the volume / frequences variations) to make some visualisations ?
Thanks in advance for your answers !

**Comment by fsbdev** [comment]
see https://github.com/audiocogs/aurora.js/issues/94

**Comment by puluch** [comment]
A bit late... I'm not really understanding this post, is there a way to get the audioNode or the audioContext from Aurora to analyse it ?
