### ISSUE TITLE
How to play the live stream delay less.

### ISSUE THREAD

**Issue by DavidLyu2008** [audiocogs/aurora.js#133]
Hello, 
I try to play a live aac stream via websocket, it can play now, but there is a problem, it delay 5-7 second. 
I don't know how to let the player play sound delay less.

Thanks
David

**Comment by fsbdev** [comment]
Are you streaming a file? If so does your server throttle the stream to the
client? It could be sending the data too quickly which I've seen leads to
such delays because it sends the entire file before playback is able to
begin.

**Comment by DavidLyu2008** [comment]
No, My Websocket server forward the data quickly, while the data sends from ffmpeg, and the video ha s not delay, but the audio has a big delay.

here is the server's codes:
```javascript
var streamServer = require('http').createServer( function(request, response) {
		request.on('data', function(data){
			socketServer.broadcast(data, {binary:true});
		});

}).listen(STREAM_PORT);
```

And I found that the memory increases rapidly up, I only add these codes in html:
    var player = AV.Player.fromWebSocket('ws://127.0.0.1:8084/');
    player.play();

the memory almost get 180M. 

Thanks
David

**Comment by DavidLyu2008** [comment]
Sorry for report the memory problem, it has not that problem.
Maybe it caused by open the chrome dev tools and output some variables of player to console.

**Comment by fsbdev** [comment]
Can you add throttling to your audio server stream like is done in the
server example for the aurora websocket repo?

**Comment by DavidLyu2008** [comment]
No, @fsbdev , the audio stream is alway sending, it hasn't a done flag. 
I want to play the adts(aac) stream as quick as the player can. 
But I don't know how to do that.

I saw your server's code of demo, it reads a file and send the stream to client when the client request a file. server knows the file's size, but our server don't know, because the stream is from ffmpeg that is capturing from microphone.

Thanks for reply.
David

**Comment by fsbdev** [comment]
Okay, try adding throttling for your audio like done here https://github.com/fsbdev/aurora-websocket/blob/master/server-examples/node/aurora-ws-server.coffee#L49. 
It still might help. Don't worry about it slowing playback down because I think right now it is sending data more quickly than the client can handle anyway.

**Comment by DavidLyu2008** [comment]
I have modified the AV.Queue to let it delay less 2 second, the queue returns the latest frame in its 'read' function. it is a hack way.

I found the 'readyMask' is 64, it means player must adds 64 frame to it and then begin to start playing. if it has not received end mask.

But it has a unknown issue, the player plays some time(10-20 minutes), it auto stoped.

**Comment by DavidLyu2008** [comment]
I need modify the interval of AudioDevice's updateTime, the default value is 200ms, it is too big, I changed it to 30ms.
Everything seems OK,  the longer the audio plays, the longer the delay.
I need the audio plays synchronous with video plays.

Ah..., it is a big problem.

**Comment by DavidLyu2008** [comment]
I have tried to re-initialize audioContext per 100s to fix this issue. It works well, 
Thanks @fsbdev

**Comment by devongovett** [comment]
Sounds like a possible bug... Can you explain the problem/solution more? Not sure I understand exactly what the problem was, and how you fixed it. Thanks!

**Comment by DavidLyu2008** [comment]
Hi @devongovett 
The problem description: 
   At first, the video and audio are synchronous, some seconds age(200s), the video plays, and the audio plays after 2s, the video and audio are not synchronous,

     I found  the AV.Player.currentTime doesn't equal AudioContext's currentTime, `AudioDevice`'s `updateTime` has this code `(time - this._lastTime) / this.device.sampleRate * 1000 |0`, it discards decimal places. so I modify this issue. but the problem still exist.  I have no idea about the reason.
So I use the method of violence: recreate the AudioContext, and reset the time.
 
Here is the codes:
```javascript
        AudioDevice.prototype._reCreateDevice = function(){
            console.log("call recreateDevice.");
            //destroy current device
            this.device.off('refill', this.refill);
            clearInterval(this._timer);
            this.device.destroy();

            //create a new device
            this.device = AV.AudioDevice.create(this.sampleRate, this.channels);
            if (!this.device)
                throw new Error("No supported audio device found.");
            this._lastTime = this.device.getDeviceTime();
            this.currentTime = 0;
            this._timer = setInterval(this.updateTime, 20); //default is 200
            return this.device.on('refill', this.refill = (function(_this) {
                return function(buffer) {
                    return _this.emit('refill', buffer);
                };
            })(this));
        };

        AudioDevice.prototype.updateTime = function() {
            var time;
            time = this.device.getDeviceTime();
            var dt = (time - this._lastTime) / this.device.sampleRate * 1000;
            this._remainder += dt - (0|dt);
            dt = (0|dt);
            if(this._remainder > 1){
                dt += 1;
                this._remainder -= 1;
            }

            this.currentTime += dt;
            this._lastTime = time;
            if(this.currentTime > 120000){ //recreate WebAudioDevice
                this._reCreateDevice();
            }
            return this.emit('timeUpdate', this.currentTime);
        };
```

Please give me a better solution.

Thanks
David

**Comment by fsbdev** [comment]
That’s not what I meant by throttling the server’s audio stream. You have a very strange solution haha.

On June 29, 2015 at 6:29:18 PM, David (notifications@github.com) wrote:

Hi @devongovett
The problem description:
At first, the video and audio are synchronous, some seconds age(200s), the video plays, and the audio plays after 2s, the video and audio are not synchronous,

 I found  the AV.Player.currentTime doesn't equal AudioContext's currentTime, `AudioDevice`'s `updateTime` has this code `(time - this._lastTime) / this.device.sampleRate * 1000 |0`, it discards decimal places. so I modify this issue. but the problem still exist.  I have no idea about the reason.

So I use the method of violence: recreate the AudioContext, and reset the time.

Here is the codes:

        AudioDevice.prototype._reCreateDevice = function(){
            console.log("call recreateDevice.");
            //destroy current device
            this.device.off('refill', this.refill);
            clearInterval(this._timer);
            this.device.destroy();

            //create a new device
            this.device = AV.AudioDevice.create(this.sampleRate, this.channels);
            if (!this.device)
                throw new Error("No supported audio device found.");
            this._lastTime = this.device.getDeviceTime();
            this.currentTime = 0;
            this._timer = setInterval(this.updateTime, 20); //default is 200
            return this.device.on('refill', this.refill = (function(_this) {
                return function(buffer) {
                    return _this.emit('refill', buffer);
                };
            })(this));
        };

        AudioDevice.prototype.updateTime = function() {
            var time;
            time = this.device.getDeviceTime();
            var dt = (time - this._lastTime) / this.device.sampleRate * 1000;
            this._remainder += dt - (0|dt);
            dt = (0|dt);
            if(this._remainder > 1){
                dt += 1;
                this._remainder -= 1;
            }

            this.currentTime += dt;
            this._lastTime = time;
            if(this.currentTime > 120000){ //recreate WebAudioDevice
                this._reCreateDevice();
            }
            return this.emit('timeUpdate', this.currentTime);
        };
Please give me a better solution.

Thanks
David

**Comment by DavidLyu2008** [comment]
Hi @fsbdev ,

I think the problem is not send audio stream quickly.  I meant throttling the server’s audio stream, that is limit the stream too quick. but I think the reason is playing audio slowly.
