### ISSUE TITLE
Performance in chrome for android [FLAC.js]

### ISSUE THREAD

**Issue by nickcartery** [audiocogs/aurora.js#134]
Hi,

Anyone can help me resolve the problem in here?
https://github.com/audiocogs/flac.js/issues/23

I've updated Android OS to 5.0 and the newest Chrome for Anroid version, but It's still lag :( (when the monitor is turned off)

Many thanks,

**Comment by devongovett** [comment]
It's possible that Chrome for Android throttles events, or maybe your hardware is just too slow for aurora. Closing the issue for now, but let me know if you solved the issue in the meantime.
