### ISSUE TITLE
webkit browsers cache issue

### ISSUE THREAD

**Issue by VanTudor** [audiocogs/aurora.js#138]
Hi.

I just started using your library, and i am facing some issues regarding playback on the client. The first time i do var player = AV.Player.fromURL(...); and then player.play(); it works, but if i call these two methods again (after pausing or not, it acts the same), it doesn't work/play any sound, although the AV.Player.playing property does change as expected. Also, refreshing doesn't help. This happens only on Safari.

One thing i noticed is that the local storage usage increases on Safari every time i call av.player.fromurl(); and it does so on Chrome too, but the player does work on Chrome after the first method calls. 

I supose the problem is related to the way browsers cache these files after they were first requested. Is there any workaround for this?

**Comment by devongovett** [comment]
I believe that https://github.com/audiocogs/aurora.js/pull/111 should have fixed this. Let me know.

**Comment by VanTudor** [comment]
Pff.. dumped the project in the meantime. I'll come back if I start working on it again.
