### ISSUE TITLE
A way to know when the seektable is ready ? 

### ISSUE THREAD

**Issue by puluch** [audiocogs/aurora.js#140]
Hello, I would like to know if there is a way to know when the seektable of a file is ready ? I made a player with a progress bar, on the click on it, it uses the seek() function to go to a duration on the file, but on some files (mostly when I am clicking just after playing the file) the player crashes (with no error returned). I saw that on these files, if I am waiting for 2 to 5 seconds before triggering the seek(), it works. Any idea ?

**Comment by puluch** [comment]
In fact, the problem seemed to be that I was using "too precise" seekpoints in ms, so sometimes, I guess the seekpoint was too hard to find for the player. To fix that, I just used a Math.floor(durationInMs / 1000) to convert it to seconds then I multiplied back the duration by 1000 -> my entry point could be 12587 it will be transformed to 12000. For now it seems to be working on both mp3 and flac files.
Sorry for my bad english.

**Comment by fsbdev** [comment]
If that's the case then the framework should round the number inside the seek method rather than having the user do it otherwise people will continue to run into this issue.
You can reopen this issue or make a new one.

**Comment by puluch** [comment]
I'm using the browserified version, adding these 2 lines at the begining of this prototype do the trick (I'm a sunday developper so I don't use coffeeScript if someone wants to push it he will be welcome) :
````javascript
Stream.prototype.seek = function(position) {
        //Just added these 2 lines :
        position = Math.floor(position/1000);
        position = position*1000;
        if (position > this.offset) {
            return this.advance(position - this.offset);
        } else if (position < this.offset) {
            return this.rewind(this.offset - position);
        }
    };
````

**Comment by fabienbrooke** [comment]
You can learn a little CoffeeScript and make a PR :) just make sure to have a comment before those lines to say that you are converting to a whole seconds value.

**Comment by devongovett** [comment]
Not sure I get this issue/fix. The change you made was to the stream class, which seeks in bytes, not milliseconds, so this rounding doesn't make sense to me...

Going to close this for now, but let me know if you have more info.
