### ISSUE TITLE
Codecs?Containers?

### ISSUE THREAD

**Issue by wilsonlmh** [audiocogs/aurora.js#145]
The documentation has a bit mistake in this pages:
https://github.com/audiocogs/aurora.js/wiki/Known-Uses
Demuxer and decoder weren't same thing in properly speaking. For user like me, I hope to know if mp4 container was supported. But I can only found AAC(which always contain in mp4, but sometimes not) codecs in document. You know AAC can contain in m4a, mts, m4r, m2t, mov, mkv, flv, avi, aac and more. So may I suggest you to split them into two list: `demuxer` and `decoder`. It's better for users and even developers to develop new demuxer. Thanks for that!

**Comment by devongovett** [comment]
The m4a demuxer is built in. The AAC codec is separate, which is why it is listed on that page.

**Comment by wilsonlmh** [comment]
You aren't completely correct. m4a dumxer in only bulit in **some** browsers but not all(like chromium). Here's my project fiveLoadSub (wilsonlmh.github.io/fiveLoadSub). I'm facing issue for decoding large file cause crash. Because I can't control the process of demuxing/decoding. I'm heading for a chunking solution(demux, split to pieces and remux without decoding). My friend recommended your project which is great and extensible to solve my problem. And I guess controllable demuxer and decoder are also dream for every JS-er.

**Comment by devongovett** [comment]
built into aurora.js, not the browser. https://github.com/audiocogs/aurora.js/blob/master/src/demuxers/m4a.coffee

**Comment by wilsonlmh** [comment]
OK, great! Thanks for you information.
