### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by clonq** [audiocogs/aurora.js#153]
$ npm install av
> speaker@0.0.10 install /test/node_modules/av/node_modules/speaker
> node-gyp rebuild

  CC(target) Release/obj.target/output/deps/mpg123/src/output/coreaudio.o
  LIBTOOL-STATIC Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:6:
../src/node_pointer.h:23:9: error: unexpected namespace name 'Buffer': expected expression
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);

  ...

  fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1

Any hints?

**Comment by crackofdusk** [comment]
It may be related to https://github.com/audiocogs/aurora.js/pull/137

@devongovett ?

**Comment by devongovett** [comment]
Yes, merged that PR and released v0.4.6 to npm. Installs for me now.

**Comment by clonq** [comment]
Yep, it works. Thanks!
