### ISSUE TITLE
Web Worker for AV.Asset.decodeToBuffer

### ISSUE THREAD

**Issue by mon** [audiocogs/aurora.js#155]
I'm using Aurora as a replacement for decodeAudioData because it's consistent (cross browser gapless MP3 is impossible without it). However, it freezes the page while it decodes. Is it possible to have decodeToBuffer use a Web Worker for nonblocking decodes?

**Comment by DeusExLibris** [comment]
This is certainly possible.  While I haven't moved that particular code to a web worker, I did integrate websocket-aurora as a source and created both worker and non-worker versions.  You can find the fork here - [Aurora with WS Worker](https://github.com/DeusExLibris/aurora.js).  Look in src/sources/wsWorker.coffee for an example.  The web worker is in the root (note that this uses transferable objects to minimize the overhead of passing data between the worker and the main code).

**Comment by mon** [comment]
Very neat! I ended up making a [simple worker wrapper](https://github.com/mon/0x40-web/blob/master/lib/workers/audio-worker.js) with transferrables. Not quite as attractive as your solution, but worked for my needs.

**Comment by devongovett** [comment]
We don't have support for workers built in, but it's pretty easy to make your own worker script with aurora in it and do the decoding there yourself. We may move to working decoding by default if we ever get support for the web audio API there. See #105.
