### ISSUE TITLE
Audio not playing on mobile Safari

### ISSUE THREAD

**Issue by tanghia** [audiocogs/aurora.js#157]
Dear

I have a problem with mobile devices, my website plays with flac & mp3 on pc very well, however  my website can't not play on IPhone (safari 9 and chrome). IPAD (safari 9 and chrome). I see that music file from url is loaded, its metadata is displayed, even i can "seek" time on progress bar.

This problem make me stuck.

Thank for any support

**Comment by crackofdusk** [comment]
Hello @tanghia 

Can you try playing an mp3 with the player on http://audiocogs.org/codecs/mp3/ with your mobile devices? If it plays successfully, you may want to check what you are doing differently in your own code.

**Comment by tanghia** [comment]
Thank crackofdush,
I tried playing  mp3 files with the player on  http://audiocogs.org/codecs/mp3/ and my website. The player had same results on mobile devices. The player can load everthing of file but can't play it. I'm sure that i didn't change any code block in core lib.   

I fixed some hard issues. However, i think that this issue need **a person who has deeper knowledge about aurora.js to resolve it, not me**

this is my test website [http://ilossless.com/](url), run on pc well, but fail on ios.

**Comment by crackofdusk** [comment]
I cannot confirm the playback problems since I don't have any iOS devices.

(For the record, I can play mp3s on http://audiocogs.org/codecs/mp3/ with Chrome for Android.)

**Comment by tanghia** [comment]
My problem is same as https://github.com/audiocogs/flac.js/issues/25  . If this issue can be resolved, i will really happy :).
Thank you for support.

**Comment by crackofdusk** [comment]
According to the [iOS specific consideration](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html) section of the Safari documentation, playback needs to be initiated by the user also for Web Audio (I previously thought it only applied to `<audio>` and `<video>` tags).

What this means is that you cannot start playing from a callback when the track has been downloaded. The user has to press play again (Try it!).

In addition, it seems that `touchstart` can no longer be used to initiate playback: https://bugs.webkit.org/show_bug.cgi?id=149367 One needs to use `touchend`.

I don't think we can do anything about this in aurora.js.
@devongovett ?

**Comment by tanghia** [comment]
Thank you, 
i think i will find a solution to initiate touch event (use js), this is last hope in the current time.
