### ISSUE TITLE
Browser builds include node/http and node/file

### ISSUE THREAD

**Issue by laurence-myers** [audiocogs/aurora.js#161]
Running "make js" followed by "make browser" or "make browser_slim" will include these files in the merge output:

- src/sources/node/http
- src/sources/node/file

The resulting output file can't be used in the browser, as it contains invalid references to "fs" and "fs.stat".

The imports should use their equivalent files from the "src/sources/browser" directory.

There is a comment in aurora_base.coffe:

> \# browserify will replace these with the browser versions

This doesn't seem to be happening.

I can workaround it by changing lines 10 and 11 of files asset.coffee and aurora_base.coffee, but this obviously breaks node.js functionality.

**Comment by devongovett** [comment]
Should be fixed by https://github.com/audiocogs/aurora.js/commit/8ea21f43811e2b1dab48798f476363f7e44d264f.
