### ISSUE TITLE
Compiling into WebAssembly

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [audiocogs/aurora.js#164]
vorbis.js, opus.js, ogg.js ported using emscripten to asm.js.

What about compiling them to WebAssembly?

There are experimental native WebAssembly implementations for Google Chrome, Mozilla Firefox, Microsoft Edge and Apple Safari.

**Comment by devongovett** [comment]
This doesn't really apply to aurora.js directly, but rather to the projects you listed above. I don't have time to try that out myself, but let me know if you do it. I'm interested to hear how it goes. :)
