### ISSUE TITLE
IOS Play Audio

### ISSUE THREAD

**Issue by sassyn** [audiocogs/aurora.js#165]
Hi All,

Well I manage to use Aurora web socket implementation and play a stream from FFMPEG.
I'm using both mp3 and aac raw data.

It seems to be working fine, but in IOS - i can't make it work.
No error, nothing! and I can't hear a thing in the speaker.

Is this working on IOS device? 

Android/Chrome/Firefox/IE did worked but IOS not!

anyidea?

**Comment by crackofdusk** [comment]
Hello,

Check my answer about iOS here: https://github.com/audiocogs/aurora.js/issues/157#issuecomment-176934700

**Comment by sassyn** [comment]
Thank You.
I know this issue but it seems even if I do a button and click it is not working:

<script type='text/javascript'>
 $('#audio').on('touchstart touchend', function(e) {
	console.log(start audio);
        audio_on();
   });
<script type='text/javascript'>
 $('#audio').on('touchstart touchend', function(e) {
	console.log(1111);
        audio_on();
       
    });
window.onload = function(){
	}


<script type="text/javascript">
audio_on = function(){
var wsUrl = "ws://x.y.x.z:9080",
    wsFile = "file.mp3";
   var player = AV.Player.fromWebSocket(wsUrl, wsFile);
   player.play();
	console.log('in audio_on func');
}
</script>


What am I doing wrong?
Can you please provide an example?
I'mon this issue for 2 weeks without any solution. :-(
