### ISSUE TITLE
could not find module 'coffeeify'

### ISSUE THREAD

**Issue by agentfitz** [audiocogs/aurora.js#166]
Hey guys,

I use browserify in my app, so I tried to follow along with the two simple steps as you described them:

```
npm install av --save-dev
npm install mp3 --save-dev
```

And then pull aurora into my application
```
var av = require('av');
var mp3 = require('mp3');
```

But when I attempt to run my app's build, it fails with this output:

```
Error: Cannot find module 'coffeeify' from '/Users/brian/gdrive/www/lexo/site/wwwroot/node_modules/av'
    at /Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/brian/myapp/wwwroot/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any idea where I went wrong? Thank you

**Comment by agentfitz** [comment]
Ah, well installing coffeeify did the trick, but that was a bit surprising that I had to do that since normally I think packages pull in their own subpackages? :shrugs:

Anyway, thanks for building Aurora, I really hope it helps me solve this VERY troublesome issue I'm dealing with about long MP3 files (8+ minutes) misreporting/mis-setting their currentTime attribute.

**Comment by devongovett** [comment]
Made `coffeeify` an explicit dependency instead of only a dev dependency in https://github.com/audiocogs/aurora.js/commit/394711debdea76339c5f4858b496079259204797. That way it will be installed when aurora is installed as a sub-dependency of another project.
