### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ohtangza** [audiocogs/aurora.js#184]
Any hope?

**Comment by devongovett** [comment]
Not dead. We have limited time to work on it though. It's a spare time project. Here's a discussion of the future of the project: https://github.com/audiocogs/aurora.js/issues/170. What are you looking for that we don't already support?

**Comment by ohtangza** [comment]
@devongovett Thanks for your response. I was surprised that you answered this fast. The open pull request for a long time made me misunderstood. No offense! I'll provide some input if I have some ideas to the issue you mentioned. Thanks for the great project and your time and effort on it.
