### ISSUE TITLE
on mobile dont work your demo

### ISSUE THREAD

**Issue by publicocean0** [audiocogs/aurora.js#190]
i tried to load a mp3 using mobile (smartphone android and ipad )in your demo... :(

**Comment by publicocean0** [comment]
i will investigate more

**Comment by crackofdusk** [comment]
This is a known limitation that is out of our hands. See https://github.com/audiocogs/aurora.js/issues/157#issuecomment-176934700

**Comment by publicocean0** [comment]
A demuxer for this container was not found. ... but on ipad i load mp3 from google drive because i ddint found a way for load from local space. They want you put your data in a external cloud grrrrrr :( i think Apple use a business logic a bit so much .... I trust in you for the checks in other mobiles.
