### ISSUE TITLE
Converting m4a to mp3 on browser

### ISSUE THREAD

**Issue by singhpratyush** [audiocogs/aurora.js#201]
I have m4a data coming from a URL and I want to convert it to mp3 on the client side. I am not sure if this use case comes under the scope of this library. If yes, please provide a reference to how this can be done.

Thanks in advance :smile:.

**Comment by crackofdusk** [comment]
Hi,

To transcode from AAC to MP3, you need two steps:
1. *decode* the AAC stream to raw audio. aurora.js supports this with https://github.com/audiocogs/aac.js
2. *encode* the uncompressed audio to MP3. aurora.js does not support this.

You need to find a mp3 encoder library. Maybe https://www.npmjs.com/package/lamejs ? Additionally, check out the [aurora.js documentation](https://github.com/audiocogs/aurora.js/wiki) for the decoding part.
