### ISSUE TITLE
24bit audio playback

### ISSUE THREAD

**Issue by VladimirSemenyuk** [audiocogs/aurora.js#25]
Greetings!
I'm trying to play 24bit audio files on your demo (88200 Hz, 96000, 192000, both Flac and Alac). And I'm receiving a message, that the format is not supported. 
Is there any way to make aurora.js play these files?

**Comment by devongovett** [comment]
As of https://github.com/audiocogs/flac.js/commit/53e3f7c5387d1d2c672451d9b0af9e885a57366e 24 bit flac files are supported. ALAC.js still has no support for 24 bit files. See https://github.com/audiocogs/alac.js/issues/13.
