### ISSUE TITLE
AV.Player#pause() not working right in node environment

### ISSUE THREAD

**Issue by chrismangum** [audiocogs/aurora.js#73]
I wrote a script that takes an argument of a media file path, and passes aurora a buffer:
```coffeescript
fs = require 'fs'

AV = require './nodeAurora.js'
AV.require.apply null, [
  './flac.js'
  './mp3.js'
  './aac.js'
]

player = {}
fs.readFile process.argv[2], (err, data) ->
  throw err if err
  player = AV.Player.fromBuffer new Uint8Array data
  player.play()
  setTimeout (->
    player.pause()
  ), 5000
```
Playing works as expected, but when player.pause is called in the timeout, the current audio frame seems to be repeatedly sent to the audio device (producing a jarring sound). Subsequently calling player.play resumes normal playback. The codec doesn't seem to matter; I tested with mp3 and aac files. Is this a bug or am I doing something dumb?

Thanks.

**Comment by cobalamin** [comment]
Still an issue here :(

**Comment by richardlevy** [comment]
I've got this too-o-o-o-o-o-o-o-o-o-o (see what I did there!)

Would really appreciate a fix.  Thanks

**Comment by devongovett** [comment]
Looks fixed by https://github.com/audiocogs/aurora.js/commit/bfd1c54fbdd505efef4257ec39ffb1ff1a03e5a0
