### ISSUE TITLE
Add aurora.js to Travis CI

### ISSUE THREAD

**Issue by crackofdusk** [audiocogs/aurora.js#76]

**Comment by crackofdusk** [comment]
@devongovett I started working on this: see https://travis-ci.org/audiocogs/aurora.js/builds/98667397 (a build of the `travis` branch)

The problem is that it doesn't report test failures. I also tried to breaking a test locally, but the failure was not reported when testing with Node. Could you take another look at the [tests readme](https://github.com/audiocogs/aurora.js/blob/e69e3fbdfc7c8864823185cdd764f5c2dee1e273/tests/README.md) to confirm that the setup described there is correct?

**Comment by devongovett** [comment]
#168 should fix the tests. Let me know what you think.
