### ISSUE TITLE
Compiled js doesn't work: `fs.stat` undefined

### ISSUE THREAD

**Issue by pellaeon** [audiocogs/aurora.js#95]
I followed the instructions but the compiled js doesn't work. When trying to play a file the browser shows the error message `Uncaught TypeError: undefined is not a function`.
I set a breakpoint on line 10255, turns out `fs.stat` is undefined.
The compiled source code is here: https://gist.github.com/pellaeon/29983beaa33f5f6650b3

**Comment by laser** [comment]
@j0rd FWIW, I am receiving the same error (that `fs` is not defined).
