### ISSUE TITLE
Playing cached track in Safari

### ISSUE THREAD

**Issue by Mikefluff** [audiocogs/aurora.js#99]
After full preload of a track it looks like Safari caches it by default, so aurora object can't play this cached track anymore (before cleaning up the cache) if it is a Flac track file (flac.js codec), or play the only last 10 second of the track if it's a mp3 track file (mp3.js codec).

**Comment by devongovett** [comment]
Looks fixed by https://github.com/audiocogs/aurora.js/pull/111.
